# Generated by Django 5.0.6 on 2024-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Management",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("deadline", models.DateTimeField()),
            ],
            options={
                "db_table": "management",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("username", models.CharField(max_length=150)),
                ("objectif", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("vote", models.IntegerField(default=0)),
                ("image", models.URLField()),
            ],
            options={
                "db_table": "problems",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("picture", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
